/**
 * Иконки разделов сайдбара (по href). Вынесено из layout, чтобы переиспользовать
 * на «Главной»-хабе (Этап 9) — Next запрещает экспорт произвольных значений из layout.tsx.
 */
import {
  IconArrowsExchange,
  IconBook,
  IconBook2,
  IconBooks,
  IconBrain,
  IconBuildingBank,
  IconBus,
  IconCalculator,
  IconCalendar,
  IconCalendarEvent,
  IconCalendarOff,
  IconChalkboard,
  IconChartBar,
  IconChartDots,
  IconClipboardList,
  IconFile,
  IconFolder,
  IconHome,
  IconId,
  IconMedal,
  IconMedicalCross,
  IconMessage,
  IconNews,
  IconNotebook,
  IconPalette,
  IconPresentation,
  IconRobot,
  IconRun,
  IconSchool,
  IconShield,
  IconShoppingCart,
  IconSpeakerphone,
  IconStar,
  IconTable,
  IconTool,
  IconToolsKitchen2,
  IconTrophy,
  IconUsers,
  IconUsersGroup,
  IconVideo,
  IconAlertTriangle,
  IconFlame,
} from '@tabler/icons-react';

export const SIDEBAR_ICONS: Record<string, React.ComponentType<{ size?: number; stroke?: number }>> = {
  // Разделы-обёртки (сворачиваемые группы сайдбара)
  '/g/intake': IconUsersGroup,
  '/g/students': IconUsers,
  '/g/academics': IconBook2,
  '/g/finance': IconCalculator,
  '/g/psy': IconBrain,
  '/g/zvr': IconAlertTriangle,
  '/g/hr': IconId,
  '/g/life': IconSchool,
  '/g/comms': IconMessage,
  '/g/admin': IconShield,
  '/call-center': IconSpeakerphone,
  '/diary': IconNotebook,
  '/today': IconCalendarEvent,
  '/agent': IconRobot,
  '/founder': IconBuildingBank,
  '/journal': IconBook2,
  '/home': IconHome,
  '/dashboard': IconChartBar,
  '/core': IconChartDots,
  '/admission': IconUsersGroup,
  '/knowledge': IconBooks,
  '/calendar': IconCalendar,
  '/classes': IconSchool,
  '/academic-periods': IconCalendarEvent,
  '/substitutions': IconArrowsExchange,
  '/time-off': IconCalendarOff,
  '/curriculum-plan': IconClipboardList,
  '/study-plan': IconBook,
  '/schedule': IconTable,
  '/grading': IconStar,
  '/homework': IconNotebook,
  '/students': IconUsers,
  '/teachers': IconChalkboard,
  '/roles': IconShield,
  '/chats': IconMessage,
  '/reports': IconChartBar,
  '/achievements': IconTrophy,
  '/olympiads': IconMedal,
  '/portfolio': IconFolder,
  '/phys-norms': IconRun,
  '/events': IconCalendarEvent,
  '/studios': IconPalette,
  '/trips': IconBus,
  '/staff': IconId,
  '/documents': IconFile,
  '/news': IconNews,
  '/applications': IconFile,
  '/surveys': IconClipboardList,
  '/tests': IconClipboardList,
  '/curriculum-plan/my': IconNotebook,
  '/lesson-plans': IconChalkboard,
  '/presentations': IconPresentation,
  '/meals': IconToolsKitchen2,
  '/consents': IconId,
  '/lost-found': IconFolder,
  '/urgent-issues': IconAlertTriangle,
  '/incidents': IconFlame,
  '/zvr/incidents': IconAlertTriangle,
  '/zvr/family': IconUsersGroup,
  '/library': IconBooks,
  '/analytics': IconChartDots,
  '/workspace/speech': IconSpeakerphone,
  '/workspace/psychologist': IconBrain,
  '/workspace/medical': IconMedicalCross,
  '/workspace/parents': IconUsers,
  '/workspace/accounting': IconCalculator,
  '/workspace/kitchen': IconToolsKitchen2,
  '/workspace/maintenance': IconTool,
  '/media': IconVideo,
  '/purchase-requests': IconShoppingCart,
};
